POST http://localhost:8080/realms/IncidentManagement/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=incident-service&client_secret=A9IKmGjuzl6s7YeG8oOwurSPdCgxWqSF&username=admin&password=admin&grant_type=password
